export const DUMMY_DATA = [
  {
    id: "0001",
    name: "Ash",
    age: "17",
    pokemonNumber: "15",
    badges: "7",
    color: 6,
    pokemons: [
      { name: "ditto" },
      { name: "turtwig" },
      { name: "bulbasaur" },
      { name: "arceus" },
      { name: "charmander" },
      { name: "charmeleon" },
      { name: "squirtle" },
      { name: "caterpie" },
      { name: "torterra" },
      { name: "chimchar" },
      { name: "piplup" },
      { name: "butterfree" },
      { name: "sandile" },
      { name: "mew" },
      { name: "eevee" },
      { name: "pikachu" },
    ],
  },
  {
    id: "0002",
    name: "Donn",
    age: "17",
    pokemonNumber: "5",
    badges: "2",
    color: 8,
    pokemons: [
      { name: "squirtle" },
      { name: "caterpie" },
      { name: "torterra" },
      { name: "chimchar" },
      { name: "piplup" },
    ],
  },
  {
    id: "0003",
    name: "Brock",
    age: "22",
    pokemonNumber: "10",
    badges: "5",
    color: 5,
    pokemons: [
      { name: "squirtle" },
      { name: "caterpie" },
      { name: "torterra" },
      { name: "chimchar" },
      { name: "piplup" },
      { name: "butterfree" },
      { name: "sandile" },
      { name: "mew" },
      { name: "eevee" },
      { name: "pikachu" },
      { name: "litten" },
    ],
  },
  {
    id: "0004",
    name: "Misty",
    age: "22",
    pokemonNumber: "8",
    badges: "2",
    color: 0,
    pokemons: [
      { name: "ditto" },
      { name: "turtwig" },
      { name: "bulbasaur" },
      { name: "arceus" },
      { name: "charmander" },
      { name: "charmeleon" },
      { name: "squirtle" },
      { name: "caterpie" },
      { name: "torterra" },
    ],
  },
  {
    id: "0007",
    name: "Arna",
    age: "30",
    pokemonNumber: "15",
    badges: "10",
    color: 2,
    pokemons: [
      { name: "turtwig" },
      { name: "bulbasaur" },
      { name: "arceus" },
      { name: "charmander" },
      { name: "charmeleon" },
      { name: "squirtle" },
      { name: "caterpie" },
      { name: "torterra" },
      { name: "chimchar" },
      { name: "piplup" },
      { name: "butterfree" },
      { name: "sandile" },
      { name: "mew" },
      { name: "eevee" },
      { name: "pikachu" },
      { name: "litten" },
    ],
  },
  {
    id: "0432",
    name: "Leon",
    age: "32",
    pokemonNumber: "30",
    badges: "20",
    color: 1,
    pokemons: [
      { name: "mew" },
      { name: "eevee" },
      { name: "pikachu" },
      { name: "litten" },
    ],
  },
];
