export const POKEMONS = [
    {name: "ditto"},
    {name: "turtwig"},
    {name: "bulbasaur"},
    {name: "arceus"},
    {name: "charmander"},
    {name: "charmeleon"},
    {name: "squirtle"},
    {name: "caterpie"},
    {name: "torterra"},
    {name: "chimchar"},
    {name: "piplup"},
    {name: "butterfree"},
    {name: "sandile"},
    {name: "mew"},
    {name: "eevee"},
    {name: "pikachu"},
    {name: "litten"},
];